; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html



;[platformio]
;default_envs = teensy41


[platformio]
default_envs = teensy41

[env:teensy41]
build_flags =
  -I include
  -I lib/Sensors/qtr
  -I lib/Sensors/mux
  -I lib/Sensors/IR_mux
  -I lib/Sensors/tof
  -I lib/Sensors/IR
  -I lib/Sensors/BNO
  
platform = teensy
board = teensy41
framework = arduino

monitor_speed = 115200
monitor_filters = time

lib_deps =
  adafruit/Adafruit BusIO
  adafruit/Adafruit BNO055
  adafruit/Adafruit TCS34725
  pololu/VL53L0X
  pololu/VL53L1X 
  adafruit/Adafruit Unified Sensor
  adafruit/Adafruit BusIO
  br3ttb/PID@^1.2.1 